apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: remove-net-capabilities
  annotations:
    policies.kyverno.io/title: Remove Net Capabilities
    policies.kyverno.io/category: Pod Security Standards (Baseline)    
spec:
  rules:
  - name: remove-net-capabilities
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: request.operation || 'BACKGROUND'

        operator: AnyIn
        value:
          - CREATE
          - UPDATE
    mutate:
      foreach:
      - list: request.object.spec.containers[]
        foreach:
          - list: "element.securityContext.capabilities"
            patchesJson6902: |-
              - path: /spec/containers/{{ "{{" }}elementIndex0{{ "}}" }}/securityContext/capabilities/add/{{ "{{" }}elementIndex1{{ "}}" }}
                op: remove
                value:
                  - NET_ADMIN
          - list: "element.securityContext.capabilities"
            patchesJson6902: |-
              - path: /spec/containers/{{ "{{" }}elementIndex0{{ "}}" }}/securityContext/capabilities/add/{{ "{{" }}elementIndex1{{ "}}" }}
                op: remove
                value: 
                  - NET_RAW